language: node_js
node_js:
  - "0.12"
sudo: false
script:
  - "grunt test"
  - "grunt coverage"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7b99340d96821cb25593
    on_success: change
    on_failure: always
    on_start: false
